# Generated by Django 5.2.8 on 2025-11-09 08:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id_user', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.TextField(unique=True)),
                ('password', models.TextField()),
                ('type_user', models.BooleanField(default=False)),
                ('state_user', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UsersInfo',
            fields=[
                ('id_user_info', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('email', models.TextField()),
                ('rut', models.TextField()),
                ('born_date', models.DateField()),
            ],
            options={
                'db_table': 'users_info',
                'managed': False,
            },
        ),
    ]
