# Generated by Django 5.2.8 on 2025-11-09 11:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id_product', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('price_sale', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('image', models.BinaryField(blank=True, null=True)),
                ('price_buy', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'products',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id_sale', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_sale', models.DateField()),
                ('items', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pay_method', models.TextField()),
                ('state', models.BooleanField(default=True)),
                ('utility', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'sales',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SalesBag',
            fields=[
                ('id_sales_bag', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantitity', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'sales_bag',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SalesMovement',
            fields=[
                ('id_movement', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type_movement', models.TextField()),
                ('type_action', models.TextField()),
                ('date_movement', models.DateField()),
            ],
            options={
                'db_table': 'sales_movement',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Stores',
            fields=[
                ('id_store', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('direction', models.TextField()),
                ('phone', models.TextField()),
                ('adminstrator_name', models.TextField()),
            ],
            options={
                'db_table': 'stores',
                'managed': False,
            },
        ),
    ]
