# Generated by Django 5.2.8 on 2025-11-09 12:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_products_sales_salesbag_salesmovement_stores'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id_category', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name_category', models.TextField()),
            ],
            options={
                'db_table': 'category',
                'managed': False,
            },
        ),
    ]
