# Generated by Django 5.2.8 on 2025-11-10 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuperAdmin',
            fields=[
                ('username', models.TextField(primary_key=True, serialize=False)),
                ('password', models.TextField()),
            ],
            options={
                'db_table': 'super_admin',
                'managed': False,
            },
        ),
    ]
